config/routes.rb
MailsViewer::Engine.routes.draw do
  controller "home" do
    get "/index", to: :index
    get "/raw", to: :raw
    get "/html", to: :html
    get "/plain", to: :plain
    get '/attachment', to: :attachment
  end
  root to: 'home#index'
end

app/controllers/mails_viewer/home_controller.rb
module MailsViewer
  class HomeController < ActionController::Base
    layout false
    before_filter :disabled_on_production
    before_filter :find_absolute_filename, only: [:raw, :html, :attachment, :plain]

    def index
      Dir.chdir(mails_path) do
        @mails = Dir["**/*"]
          .select{|f| File.file?(f)}
          .map{|f| [Mail.read(f), f]}
      end
    end

    def raw
      if @filename
        render text: File.read(@filename)
      else
        head :not_found
      end
    end

    def html
      if @filename
        mail = Mail.read(@filename)
        body = mail.html_part ? mail.html_part.body : mail.body
        render text: body
      else
        head :not_found
      end
    end

    def plain
      if @filename
        mail = Mail.read(@filename)
        @body = mail.text_part ? mail.text_part.body.to_s : mail.body.to_s
      else
        head :not_found
      end
    end

    def attachment
      if @filename
        mail = Mail.read(@filename)
        attachment = mail.attachments[params[:attachment]]

        if attachment
          send_data attachment.body.decoded, filename: params[:attachment], type: attachment.content_type and return
        end
      end

      head :not_found
    end

  private
    def mails_path
      @mails_path ||= File.expand_path(Rails.application.config.action_mailer.file_settings.try(:[], :location) || './tmp/mails',
                                       Rails.root)
    end

    def disabled_on_production
      if Rails.env == 'production' || Rails.application.config.action_mailer.delivery_method.to_sym != :file
        render text: 'Mails Viewer is disabled' and return false
      end
    end

    def find_absolute_filename
      if params[:filename].present?
        filename = File.expand_path(params[:filename], mails_path)

        # ensure the file is in mails_path
        if filename == File.join(mails_path, params[:filename])
          @filename = filename
        end
      end
    end

  end
end

app/views/mails_viewer/home/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mailer</title>
  <%= stylesheet_link_tag "mails_viewer" %>
  <%= javascript_include_tag "mails_viewer" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="container">
    <div id="list">
      <table class="tablesorter">
        <thead><tr><th>From</th><th>To/cc/bcc</th><th>Subject</th><th>Date</th></thead>
        <tbody>
          <% @mails.each do |mail, filename| %>
            <tr class="mail">
              <td><%= mail.from.join(', ') %></td>
              <td>
                <%= (mail.to || []).join(', ')  %> /
                <%= (mail.cc || []).join(', ')  %> /
                <%= (mail.bcc || []).join(', ')  %>
              </td>
              <td>
                <%= mail.subject %>
                <% if mail.html_part || mail.content_type =~ /html/ %>
                  <a href="<%= email_path(filename, :html) %>" class="html preview">html</a>
                <% end %>
                <% if mail.text_part || mail.content_type =~ /plain/ %>
                  <a href="<%= email_path(filename, :plain) %>" class="plain preview">plain</a>
                <% end %>

                <% mail.attachments.each do |attachment| %>
                  <a href="<%= attachment_path(filename, attachment.filename) %>" class="attachment preview"><%= attachment.filename %></a>
                <% end %>
                <a href="<%= email_path(filename, :raw) %>" class="raw">raw</a>
              </td>
              <td><%= mail.date.to_s(:long) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <div id="pager" class="pager">
        <form>
          <input type="text" class="pagedisplay"/>
          <select class="pagesize">
            <option selected="selected"  value="10">10</option>
            <option value="20">20</option>
            <option value="30">30</option>
            <option  value="40">40</option>
          </select>
          <img src="/assets/tablesorter/first.png" class="first"/>
          <img src="/assets/tablesorter/prev.png" class="prev"/>
          <img src="/assets/tablesorter/next.png" class="next"/>
          <img src="/assets/tablesorter/last.png" class="last"/>
        </form>
      </div>
    </div>

    <pre id='raw'>
      <h3>Click link above to view original email content here!</h3>
      <div></div>
    </pre>
  </div>
</body>
</html>

app/views/mails_viewer/home/plain.html.erb
<pre><%= CGI.escapeHTML(@body) %></pre>